
images:
  - name: quay.io/operator-framework/olm
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:5a85687d4af9f674a346cf89bd251ae22a7d8b12a15e91e6710bd454adcbb746
  - name: quay.io/operator-framework/configmap-operator-registry
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:687e81a85313dbecda0c8c780454198e74f160a27fe8b2ee064c93974baf3883
  - name: quay.io/openshift/origin-kube-rbac-proxy
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:77988ac48ae4310b454503a6ad9a68516302560df62b97a7a1a59d182cca72dd

patches:
  - patch: |-
     - op: add
       path: /spec/template/spec/containers/0/env/-
       value:
         name: OPERATOR_REGISTRY_IMAGE
         value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:687e81a85313dbecda0c8c780454198e74f160a27fe8b2ee064c93974baf3883
     - op: add
       path: /spec/template/spec/containers/0/env/-
       value:
         name: OLM_IMAGE
         value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:5a85687d4af9f674a346cf89bd251ae22a7d8b12a15e91e6710bd454adcbb746
    target:
      kind: Deployment
      labelSelector: app=catalog-operator
